In [1]:
import numpy as np
import pandas as pd

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
ones = np.ones(10)

In [5]:
ones = ones * 5

In [6]:
ones

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [11]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [8]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.random.randn(25)

array([-1.21092064, -2.07832719, -0.53425723,  0.47773202,  0.62298116,
        0.11746307, -1.54495656, -2.0810496 ,  1.54071491,  1.49015713,
       -0.97613664, -0.69835368,  0.16921422, -0.7479649 , -2.08001364,
        1.07922665, -0.26844577, -0.50935913,  0.28707369, -0.67162895,
        0.06465158,  0.18710186, -1.06752333,  0.55990634, -0.29224037])

In [20]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [28]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [9]:
mat = np.arange(1,26).reshape(5,5)
mat.sum()
mat.std()

7.211102550927978

In [10]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
mat.sum(0)

array([55, 60, 65, 70, 75])

In [59]:
np.random.seed(10)
np.random.rand(1)

array([0.77132064])

In [16]:
import numpy as np
import pandas as pd
from numpy.random import randn


In [17]:
np.random.seed(101)

In [18]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'], ['W','X','Y','Z'])

In [19]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [20]:
df['sum'] = df['W'] + df['X'] + df['Y'] + df['Z']

In [62]:
df.loc['E']['sum']

5.459027811814739

In [57]:
df.loc['E','sum']

5.459027811814739

In [61]:
df.iloc[4,4]

5.459027811814739

In [63]:
df.loc[['A','B'] , ['Y','W']]

Y         W
A  0.907969  2.706850
B -0.848077  0.651118

In [67]:
df.iloc[[0,1,2] , [2,0] ]

Y         W
A  0.907969  2.706850
B -0.848077  0.651118
C  0.528813 -2.018168

In [77]:
# df.drop('sum',axis=1,inplace=True)
df.drop('E',axis=0)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [21]:
df

W         X         Y         Z       sum
A  2.706850  0.628133  0.907969  0.503826  4.746778
B  0.651118 -0.319318 -0.848077  0.605965  0.089688
C -2.018168  0.740122  0.528813 -0.589001 -1.338233
D  0.188695 -0.758872 -0.933237  0.955057 -0.548357
E  0.190794  1.978757  2.605967  0.683509  5.459028

In [22]:
booldf = df > 0
booldf

W      X      Y      Z    sum
A   True   True   True   True   True
B   True  False  False   True   True
C  False   True   True  False  False
D   True  False  False   True  False
E   True   True   True   True   True

In [24]:
# df[booldf]
df[df>0]

W         X         Y         Z       sum
A  2.706850  0.628133  0.907969  0.503826  4.746778
B  0.651118       NaN       NaN  0.605965  0.089688
C       NaN  0.740122  0.528813       NaN       NaN
D  0.188695       NaN       NaN  0.955057       NaN
E  0.190794  1.978757  2.605967  0.683509  5.459028

In [99]:
# df[df['Z']<0]
resultdf = df[df['W']>0]
resultdf['X']

W         X         Y         Z       sum
A  2.706850  0.628133  0.907969  0.503826  4.746778
B  0.651118 -0.319318 -0.848077  0.605965  0.089688
D  0.188695 -0.758872 -0.933237  0.955057 -0.548357
E  0.190794  1.978757  2.605967  0.683509  5.459028

In [118]:
# same as resultdf['X']
df[df['W']>0][['X','Y']]
df[df['W']>0].loc[['A','B']]

W         X         Y         Z       sum
A  2.706850  0.628133  0.907969  0.503826  4.746778
B  0.651118 -0.319318 -0.848077  0.605965  0.089688

In [128]:
df
df[(df['W']>0) & (df['X']>0)]

W         X         Y         Z       sum
A  2.706850  0.628133  0.907969  0.503826  4.746778
E  0.190794  1.978757  2.605967  0.683509  5.459028

In [141]:

df['states'] = 'CA NY WY OR CO'.split()
df.reset_index()
df
df.set_index('states')

W         X         Y         Z       sum
states                                                  
CA      2.706850  0.628133  0.907969  0.503826  4.746778
NY      0.651118 -0.319318 -0.848077  0.605965  0.089688
WY     -2.018168  0.740122  0.528813 -0.589001 -1.338233
OR      0.188695 -0.758872 -0.933237  0.955057 -0.548357
CO      0.190794  1.978757  2.605967  0.683509  5.459028

In [145]:
# --------------------- part 3 ------------------------
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)
hier_test = list(zip(outside,inside))

In [160]:
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [172]:
df2 = pd.DataFrame(randn(6,3),hier_index,['A','B','C'])

In [173]:
df2

A         B         C
G1 1  0.187125 -0.732845 -1.382920
   2  1.482495  0.961458 -2.141212
   3  0.992573  1.192241 -1.046780
G2 1  1.292765 -1.467514 -0.494095
   2 -0.162535  0.485809  0.392489
   3  0.221491 -0.855196  1.541990

In [184]:
df2.index.names = ['Group','Names']

In [195]:
df2.loc['G1']

A         B         C
Names                              
1      0.187125 -0.732845 -1.382920
2      1.482495  0.961458 -2.141212
3      0.992573  1.192241 -1.046780

In [201]:
df2.xs(2,level="Names")

A         B         C
Group                              
G1     1.482495  0.961458 -2.141212
G2    -0.162535  0.485809  0.392489

In [25]:
# --------------------------------------------------
# -------------- MISSING DATA HANDLING -------------
# --------------------------------------------------
d = {'A': [1,2,np.nan], 'B':[1,np.nan,np.nan], 'C':[1,2,3]}
df3 = pd.DataFrame(d,index=['X','Y','Z'])

In [26]:
df3

A    B  C
X  1.0  1.0  1
Y  2.0  NaN  2
Z  NaN  NaN  3

In [34]:
# df3.dropna()  #--> will delete a row containing NA
df3.dropna(thresh= 2) # delete missing data, threshold = number of column containing NA
df3.fillna('10') # fill missing data

# df3['A'].fillna(df3['A'].mean())  --> fill na with mean value for specific column

# df3 = df3.fillna(df3.mean())    --> fill na with mean value for the whole dataframe
# df3

# for x in df3.columns:
#     df3[x]=df3[x].fillna(df3[x].mean())
#     print(f'x = {x}\n{df3}\n')

#test iterable in pandas dataframe
for index, y in df3.iterrows():
    print(y['A'],y['B'],y['C'])

1.0 1.0 1.0
2.0 nan 2.0
nan nan 3.0


In [2]:
import pandas as pd
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}
df = pd.DataFrame(data)
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [9]:
by_company = df.groupby("Company")
by_company.describe().loc['FB']




Sales  count      2.000000
       mean     296.500000
       std       75.660426
       min      243.000000
       25%      269.750000
       50%      296.500000
       75%      323.250000
       max      350.000000
Name: FB, dtype: float64

In [11]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [12]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [13]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [16]:
pd.concat([df1,df2,df3],0)

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [17]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})    

In [28]:
pd.merge(left,right,'right','key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [29]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [33]:
pd.merge(left,right,'inner',['key1','key2'])

key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [1]:
# --------------------- Panda Input & Output ----------------
import pandas as pd
pd.read_html()